ENCRYPTION_ENABLED = False
ENCRYPTION_METHOD = None
INTEGRITY_ENABLED = False
INTEGRITY_METHOD = None
AUTH_ENABLED = False
AUTH_METHOD = None
NET = 'resnet18'
TLS = False
ACCURACY = 0.9
NUM_CLIENTS = 20
EVALUATION_SIDE = 'server'

VERBOSE_CRYPTO_STATUS = False

SERVER_EVAL_EVERY = 2
CLIENT_CPU_THREADS = 8
